### ISSUE TITLE
App will not start properly on Windows 10

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#143] opened 2021-06-21 07:37 UTC
**Describe the bug**
User is having trouble using the VPN. One day no locations showed up, so user updated to the latest version, and now it is just stuck at "starting daemon" and never starts up. 
![IMAGE 2021-06-21 08:35:16](https://user-images.githubusercontent.com/84313603/122724195-9babe700-d26b-11eb-9644-3b3d6ecb885d.jpg)

**To Reproduce**
1. Install app
2. Open it up

**Expected behavior**
App should open up as expected

 
 - OS: Windows 10
 - Desktop app version (if applicable): 4.2.1

**Additional context**

Logs:

[2021-06-13 13:00:51.832] [info] Supervisor version bundled: 0.47.1 running: 0.47.1
[2021-06-13 13:00:51.833] [info] Running supervisor version matches, skipping the upgrade
[2021-06-13 13:00:51.851] [info] No ghosts found on port 4050
[2021-06-13 13:00:51.856] [info] No ghosts found on port 44050
[2021-06-13 13:00:51.870] [info] myst supervisor tequilapi port set to: 44050
[2021-06-13 13:00:51.931] [info] Server: ok

[2021-06-13 13:01:13.438] [info] Connecting to the supervisor...
[2021-06-13 13:01:13.449] [info] Connected to:  \\.\pipe\mystpipe
[2021-06-13 13:01:13.450] [info] Stopping myst
[2021-06-13 13:01:13.451] [info] Shutting down node gracefully on port 44050
[2021-06-14 00:08:09.077] [info] Checking for update
[2021-06-14 00:08:09.909] [info] Pushy device token: 3d91ad8416a6d26884873d
[2021-06-14 00:08:10.012] [info] Update for version 4.2.1 is not available (latest version: 4.2.1, downgrade is disallowed).
[2021-06-14 00:08:10.016] [info] Connecting to the supervisor...
[2021-06-14 00:08:10.019] [info] Connected to:  \\.\pipe\mystpipe
[2021-06-14 00:08:10.063] [info] Server: ok: 0.47.1

[2021-06-14 00:08:10.064] [info] Supervisor version bundled: 0.47.1 running: 0.47.1
[2021-06-14 00:08:10.065] [info] Running supervisor version matches, skipping the upgrade
[2021-06-14 00:08:10.076] [info] No ghosts found on port 4050
[2021-06-14 00:08:10.080] [info] No ghosts found on port 44050
[2021-06-14 00:08:10.097] [info] myst supervisor tequilapi port set to: 44050
[2021-06-14 00:08:10.104] [info] Server: ok

[2021-06-14 00:08:24.754] [info] Connecting to the supervisor...
[2021-06-14 00:08:24.764] [info] Connected to:  \\.\pipe\mystpipe
[2021-06-14 00:08:24.766] [info] Stopping myst
[2021-06-14 00:08:24.767] [info] Shutting down node gracefully on port 44050
[2021-06-15 23:38:57.030] [info] Checking for update
[2021-06-15 23:38:57.885] [info] Pushy device token: 3d91ad8416a6d26884873d
[2021-06-15 23:38:57.968] [info] Update for version 4.2.1 is not available (latest version: 4.2.1, downgrade is disallowed).
[2021-06-15 23:38:57.973] [info] Connecting to the supervisor...
[2021-06-15 23:38:57.976] [info] Connected to:  \\.\pipe\mystpipe
[2021-06-15 23:38:57.997] [info] Server: ok: 0.47.1

[2021-06-10 21:18:03.756] [info] Supervisor version bundled: 0.47.1 running: 0.47.1
[2021-06-10 21:18:03.757] [info] Running supervisor version matches, skipping the upgrade
[2021-06-10 21:18:03.772] [info] No ghosts found on port 4050
[2021-06-10 21:18:03.776] [info] No ghosts found on port 44050
[2021-06-10 21:18:03.792] [info] myst supervisor tequilapi port set to: 44050
[2021-06-10 21:18:03.935] [info] Server: ok

**Comment by tadaskay** [comment] 2021-06-22 10:58
Duplicate of #144

**Closed by tadaskay** 2021-06-22 10:58 UTC
