### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by spitrip82** [mysteriumnetwork/mysterium-vpn-desktop#398] opened 2022-10-01 15:57 UTC
hello could add split tunneling to the app to be able to choose which apps will use Mysterium VPN
and which apps will use my local network?
or they could recommend a third-party app that does this split tunneling process to be able to choose which apps will use Mysterium VPN

**Comment by isaackielma** [comment] 2022-12-08 22:30
Duplicate of: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/401

**Closed by isaackielma** 2022-12-08 22:30 UTC
Labels: enhancement
